### ISSUE TITLE
Add jira integration

### ISSUE THREAD

**Issue by BodeSpezial** [BodeSpezial/chango#6]
Add field `ticket` to entries and
```toml
[jira]
projectUrl= "https://path/to/jira/project/"
```
to configuration.

## Further features

Maybe inform further which other platforms (Bitbucket, GitLab) are possible and useful to integrate? What are regularly used Git-Hosting-Services and project-management-tools?
